contact_links:
  - name: 🤔 Support Question
    url: https://qwik.dev/chat
    about: This issue tracker is not for support questions. Please post your question in the qwik-astro channel on the Discord chat. 
